config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :articles
  resources :posts
  get '/:username', to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5, maximum: 50 }
    validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_uniqueness_of :username

  validates :email, presence: true, uniqueness: true
  validates :firstname, presence: true, length: { minimum: 5}
  validates :lastname, presence: true, length: { minimum: 5}
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :firstname, :lastname])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :firstname, :lastname])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        @article = Article.find(params[:id])
       
        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end


    def destroy
        @article = Article.find(params[:id])
        @article.destroy
    
        redirect_to root_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :text, :username)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @articles = Article.all
        @parameter = Article.find_by_username(params[:username])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', root_path, :class => 'links' %>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <%= form.hidden_field :username, :value => current_user.username %>

  <p>
    <%= form.submit %>
  </p>

  <%= link_to 'Back', root_path, :class => 'links' %>
<% end %>

app/views/articles/show.html.erb
<p>
<strong>Title:</strong>
<%= @article.title %>
</p>

<p>
<strong>Text:</strong>
<%= @article.text %>
</p>

<p>
<strong>Created By:</strong>
<%= @article.username %>
</p>

<%= link_to 'Back', root_path, :class => 'links' %>
<% if current_user.username == @article.username %>
    | <%= link_to 'Edit', edit_article_path(@article), :class => 'links' %>
<% end %>

app/views/home/index.html.erb
<% name = current_user.present? ? current_user.firstname : 'Someone' %>

<% if user_signed_in? %>
    <h1>Welcome, <%= name %> </h1>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete, :class => 'links' %>
    <div>
        <%= link_to 'New article', new_article_path, :class => 'links' %>
        
        <table>
            <tr>
                <th>Title</th>
                <th>Text</th>
                <th>Created By</th>
            </tr>
            <% @articles.each do |article| %>
                <tr>
                    <td><%= article.title %></td>
                    <td><%= article.text %></td>
                    <td><%= link_to article.username, posts_path(:username => article.username), :class => 'links' %></td>

                    <td><%= link_to 'Show', article_path(article), :class => 'links' %></td>
                    <% if current_user.username == article.username %>
                        <td> | </td>
                        <td><%= link_to 'Edit', edit_article_path(article), :class => 'links' %></td>
                        <td> | </td>
                        <td><%= link_to 'Destroy', article_path(article),
                            method: :delete,
                            data: { confirm: 'Are you sure?' }, :class => 'links' %></td>
                    <% end %>
                </tr>
            <% end %>
        </table>
      </div>
<% else %>
    <%= link_to 'Sign up', new_user_registration_path %> | <%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseAuth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<% name = current_user.username === @parameter.username ? 'Your ' : @parameter.username %>

<h1><%= name %> Posts</h1>
<table>
<tr>
    <th>Title</th>
    <th>Text</th>
</tr>
    <% @articles.each do |article| %>
        <% if article.username == @parameter.username %>
            <tr>
                <td><%= article.title %></td>
                <td><%= article.text %></td>
   
                <td><%= link_to 'Show', article_path(article), :class => 'links' %></td>
                <% if current_user.username == @parameter.username %>
                        <td> | </td>
                        <td><%= link_to 'Edit', edit_article_path(article), :class => 'links' %></td>
                        <td> | </td>
                        <td><%= link_to 'Destroy', article_path(article),
                            method: :delete,
                            data: { confirm: 'Are you sure?' }, :class => 'links' %></td>
                <% end %>
            </tr>
        <% end %>
    <% end %>
</table>
<br />
<%= link_to 'Back', root_path %>